"""add_ticket_dedup_fields

Revision ID: f61ac8c0685f
Revises: 5adc22b19119
Create Date: 2026-03-22 18:40:18.983064

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f61ac8c0685f"
down_revision: str | None = "5adc22b19119"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("invoice_number", sa.String(length=100), nullable=True))
    op.add_column("tickets", sa.Column("pdf_hash", sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, "tickets", ["pdf_hash"])
    op.create_unique_constraint(None, "tickets", ["invoice_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tickets", type_="unique")
    op.drop_constraint(None, "tickets", type_="unique")
    op.drop_column("tickets", "pdf_hash")
    op.drop_column("tickets", "invoice_number")
    # ### end Alembic commands ###
